apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-deployment
  labels:
    component: web
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      hostname: boot-pod-host
      containers:
        - name: springboot-app
          image: abhisekyadav/spring-dockercompose
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: boot-pod-host
            - name: REDIS_PORT
              value: "6379"
        - name: redis
          image: redis
          imagePullPolicy: Always
          ports:
            - containerPort: 6379

